const recipes = [
  { id: 1,  name: "לחם שמרים לאט", image: "לחם שמרים לאט.JPG", category: "לחמים" },
  { id: 2,  name: "לחם שמרים תהליך מהיר", image: "לחם שמרים תהליך מהיר.JPG", category: "לחמים" },
  { id: 3,  name: "לחם תערובת גרעינים", image: "לחם תערובת גרעינים.JPG", category: "לחמים" },
  { id: 4,  name: "לחמניות אביגיל ללא חלב וחמאה", image: "לחמניות אביגיל ללא חלב וחמאה.JPG", category: "לחמניות" },
  { id: 5,  name: "לחמניות בגט", image: "לחמניות בגט.JPG", category: "לחמניות" },
  { id: 6,  name: "לחמניות הדגל של רוביו", image: "לחמניות הדגל של רוביו.JPG", category: "לחמניות" },
  { id: 7,  name: "לחמניות המבורגר", image: "לחמניות המבורגר.JPG", category: "לחמניות" },
  { id: 8,  name: "לחמניות כיפלי", image: "לחמניות כיפלי.JPG", category: "לחמניות" },
  { id: 9,  name: "לחמניות סבבוש רכות", image: "לחמניות סבבוש רכות.JPG", category: "לחמניות" },
  { id: 10, name: "לחמניות סנדוויץ רכות", image: "לחמניות סנדוויץ רכות.JPG", category: "לחמניות" },
  { id: 11, name: "לחמניות צימוקים", image: "לחמניות צימוקים.JPG", category: "לחמניות" },
  { id: 12, name: "לחמניות שמרים", image: "לחמניות שמרים.JPG", category: "לחמניות" },
  { id: 13, name: "ניויורק בייגל", image: "ניויורק בייגל.JPG", category: "בייגלס" },

  { id: 14, name: "בגט שמרים קלאסי", image: "בגט שמרים קלאסי.JPG", category: "לחמים" },
  { id: 15, name: "ביאלי לחמעג'ון", image: "ביאלי לחמעג'ון.JPG", category: "מאפים" },
  { id: 16, name: "בייגל ירדנה", image: "בייגל ירדנה.JPG", category: "בייגלס" },
  { id: 17, name: "בייגלה יבשים", image: "בייגלה יבשים.JPG", category: "מאפים" },
  { id: 18, name: "בייגלה ירושלמי", image: "בייגלה ירושלמי.JPG", category: "מאפים" },
  { id: 19, name: "בייגלה", image: "בייגלה.JPG", category: "מאפים" },
  { id: 20, name: "בריוש", image: "בריוש.JPG", category: "מתוקים" },
  { id: 21, name: "ג'בטה היבריד", image: "ג'בטה היבריד.JPG", category: "לחמים" },
  { id: 22, name: "גריסיני", image: "גריסיני.JPG", category: "מאפים" },
  { id: 23, name: "החלה של סבתא חיה", image: "החלה של סבתא חיה.JPG", category: "חלות" },
  { id: 24, name: "לחם זיתים ועגבניות מיובשות", image: "לחם זיתים ועגבניות מיובשות.JPG", category: "לחמים" },
  { id: 25, name: "לחם חיטה שמרים", image: "לחם חיטה שמרים.JPG", category: "לחמים" },
  { id: 26, name: "לחם מחמצת מיובשת", image: "לחם מחמצת מיובשת.JPG", category: "לחמים" },

  { id: 27, name: "סימיט", image: "סימיט.JPG", category: "מאפים" },
  { id: 28, name: "עוגיות ג'ינג'ר ", image: "עוגיות ג'ינג'ר.JPG", category: "מתוקים" },
  { id: 29, name: "פוגאס", image: "פוגאס.JPG", category: "מאפים" },
  { id: 30, name: "פיצה", image: "פיצה.JPG", category: "מאפים" },
  { id: 31, name: "פיתה כיס", image: "פיתה כיס.JPG", category: "מאפים" },
  { id: 32, name: "פיתה רוביו", image: "פיתה רוביו.JPG", category: "מאפים" },
  { id: 33, name: "פרנה", image: "פרנה.JPG", category: "מאפים" },
  { id: 34, name: "פרעצל", image: "פרעצל.JPG", category: "מאפים" },
  { id: 35, name: "קרקרים", image: "קרקרים.JPG", category: "מאפים" }
];

